-- Dream of All — কোডে লেখা প্রোডাক্টগুলো ডেটাবেজে তোলার স্ক্রিপ্ট
-- Supabase → SQL Editor → New query → পুরোটা পেস্ট করে Run করুন। একবারই চালাবেন।

insert into public.products
  (slug, name, gender, type, shape, price, old_price, tag, img, fabric, fit, care, colors, sizes, sort)
values
  ('w01', 'Linen Column Dress', 'women', 'Dress', 'aline', 4850, null, 'New', null, '100% washed European linen, 190gsm', 'Straight through the body, falls below the knee', 'Cold machine wash, line dry, warm iron', '[{"n":"Bone","h":"#E9E3D6"},{"n":"Clay","h":"#B98A70"},{"n":"Ink","h":"#23262C"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":38},{"size":"S","chestMin":32.5,"chestMax":35,"length":38.5},{"size":"M","chestMin":35,"chestMax":37.5,"length":39},{"size":"L","chestMin":37.5,"chestMax":40,"length":39.5},{"size":"XL","chestMin":40,"chestMax":43,"length":40}]'::jsonb, 0),
  ('w02', 'Silk-Wash Wrap Dress', 'women', 'Dress', 'wrap', 5400, null, null, null, 'Sandwashed viscose with a matte silk hand', 'True wrap with a self tie at the waist', 'Gentle wash or dry clean, cool iron', '[{"n":"Olive","h":"#5E6448"},{"n":"Plum","h":"#5C3A47"},{"n":"Sand","h":"#D6C4A8"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":42},{"size":"S","chestMin":32.5,"chestMax":35,"length":42.5},{"size":"M","chestMin":35,"chestMax":37.5,"length":43},{"size":"L","chestMin":37.5,"chestMax":40,"length":43.5},{"size":"XL","chestMin":40,"chestMax":43,"length":44}]'::jsonb, 10),
  ('w03', 'Slip Midi Dress', 'women', 'Dress', 'slip', 4200, 4900, null, null, 'Cupro-blend satin, fully cut on the bias', 'Skims the body, adjustable straps', 'Hand wash cold, hang to dry', '[{"n":"Pearl","h":"#DFD9CE"},{"n":"Slate","h":"#4A5560"},{"n":"Wine","h":"#63313A"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":46},{"size":"S","chestMin":32.5,"chestMax":35,"length":46.5},{"size":"M","chestMin":35,"chestMax":37.5,"length":47},{"size":"L","chestMin":37.5,"chestMax":40,"length":47.5},{"size":"XL","chestMin":40,"chestMax":43,"length":48}]'::jsonb, 20),
  ('w04', 'Boxy Cotton Tee', 'women', 'T-Shirt', 'tee', 1450, null, 'Best seller', null, 'Combed organic cotton, 220gsm', 'Boxy, sits at the hip', 'Machine wash warm, tumble low', '[{"n":"White","h":"#F4F2EC"},{"n":"Black","h":"#1C1E20"},{"n":"Sage","h":"#94A88F"},{"n":"Butter","h":"#E7CE94"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":24.5},{"size":"S","chestMin":32.5,"chestMax":35,"length":25},{"size":"M","chestMin":35,"chestMax":37.5,"length":25.5},{"size":"L","chestMin":37.5,"chestMax":40,"length":26},{"size":"XL","chestMin":40,"chestMax":43,"length":26.5}]'::jsonb, 30),
  ('w05', 'Poplin Oversized Shirt', 'women', 'Shirt', 'shirt', 3200, null, null, null, 'Crisp cotton poplin, mother-of-pearl buttons', 'Oversized, dropped shoulder', 'Machine wash cold, iron while damp', '[{"n":"White","h":"#F4F2EC"},{"n":"Blue Stripe","h":"#A9BFD4"},{"n":"Moss","h":"#6E7A5C"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":27},{"size":"S","chestMin":32.5,"chestMax":35,"length":27.5},{"size":"M","chestMin":35,"chestMax":37.5,"length":28},{"size":"L","chestMin":37.5,"chestMax":40,"length":28.5},{"size":"XL","chestMin":40,"chestMax":43,"length":29}]'::jsonb, 40),
  ('w06', 'Ribbed Camisole', 'women', 'Top', 'cami', 1150, null, null, null, '2×2 rib cotton-modal', 'Close fitting with a scoop neck', 'Machine wash cold, do not bleach', '[{"n":"Ivory","h":"#EEE8DC"},{"n":"Black","h":"#1C1E20"},{"n":"Cocoa","h":"#7A5F4E"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":22},{"size":"S","chestMin":32.5,"chestMax":35,"length":22.5},{"size":"M","chestMin":35,"chestMax":37.5,"length":23},{"size":"L","chestMin":37.5,"chestMax":40,"length":23.5},{"size":"XL","chestMin":40,"chestMax":43,"length":24}]'::jsonb, 50),
  ('w07', 'Georgette V-Neck Blouse', 'women', 'Top', 'blouse', 2600, null, null, null, 'Lightweight georgette with a soft drape', 'Relaxed, blouson sleeve', 'Gentle wash, cool iron', '[{"n":"Blush","h":"#DFB9AE"},{"n":"Ink","h":"#23262C"},{"n":"Fern","h":"#4F6350"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":23.5},{"size":"S","chestMin":32.5,"chestMax":35,"length":24},{"size":"M","chestMin":35,"chestMax":37.5,"length":24.5},{"size":"L","chestMin":37.5,"chestMax":40,"length":25},{"size":"XL","chestMin":40,"chestMax":43,"length":25.5}]'::jsonb, 60),
  ('w08', 'Cropped Loopback Sweat', 'women', 'Sweatshirt', 'crop', 2900, null, null, null, 'Loopback cotton terry, 320gsm', 'Cropped at the waist, ribbed hem', 'Wash inside out, dry flat', '[{"n":"Grey Melange","h":"#B3B6B2"},{"n":"Ecru","h":"#E3DCCC"},{"n":"Pine","h":"#33544B"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":17.5},{"size":"S","chestMin":32.5,"chestMax":35,"length":18},{"size":"M","chestMin":35,"chestMax":37.5,"length":18.5},{"size":"L","chestMin":37.5,"chestMax":40,"length":19},{"size":"XL","chestMin":40,"chestMax":43,"length":19.5}]'::jsonb, 70),
  ('m01', 'Heavy Cotton Crew Tee', 'men', 'T-Shirt', 'tee', 1350, null, 'Best seller', null, 'Ring-spun cotton, 240gsm, ribbed collar', 'Regular, straight body', 'Machine wash warm, tumble low', '[{"n":"White","h":"#F4F2EC"},{"n":"Black","h":"#1C1E20"},{"n":"Navy","h":"#2A3A50"},{"n":"Rust","h":"#A65B3D"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":24.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":25},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":25.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":26},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":26.5}]'::jsonb, 80),
  ('m02', 'Oxford Button-Down', 'men', 'Shirt', 'shirt', 3450, null, null, null, 'Yarn-dyed cotton oxford, button-down collar', 'Regular through the chest', 'Machine wash cold, hang dry', '[{"n":"Sky","h":"#A9C4DA"},{"n":"White","h":"#F4F2EC"},{"n":"Stone","h":"#C6BCA9"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":27},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":27.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":28},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":28.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":29}]'::jsonb, 90),
  ('m03', 'Piqué Polo', 'men', 'Polo', 'polo', 2250, null, null, null, 'Cotton piqué with a flat-knit collar', 'Trim, sits at the hip', 'Machine wash cold, reshape damp', '[{"n":"Forest","h":"#3B5A46"},{"n":"Chalk","h":"#EDE8DE"},{"n":"Charcoal","h":"#3A3E42"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":26.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":27},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":27.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":28},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":28.5}]'::jsonb, 100),
  ('m04', 'Brushed Flannel Overshirt', 'men', 'Shirt', 'shirt', 3900, null, 'New', null, 'Brushed cotton flannel, chest pocket', 'Roomy — wears over a tee', 'Machine wash warm, tumble low', '[{"n":"Rust Check","h":"#9C5238"},{"n":"Green Check","h":"#4B6047"},{"n":"Ash","h":"#767B7E"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":27},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":27.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":28},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":28.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":29}]'::jsonb, 110),
  ('m05', 'Loopback Hoodie', 'men', 'Sweatshirt', 'hoodie', 4100, null, null, null, 'Heavyweight loopback terry, 400gsm', 'Regular, kangaroo pocket', 'Wash inside out, dry flat', '[{"n":"Charcoal","h":"#35393B"},{"n":"Oat","h":"#DDD2BE"},{"n":"Navy","h":"#2A3A50"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":26},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":26.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":27},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":27.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":28}]'::jsonb, 120),
  ('m06', 'Long-Sleeve Henley', 'men', 'Top', 'henley', 2400, 2800, null, null, 'Slub cotton jersey, four-button placket', 'Regular with a slight taper', 'Machine wash cold, tumble low', '[{"n":"Oat","h":"#DDD2BE"},{"n":"Black","h":"#1C1E20"},{"n":"Clay","h":"#B98A70"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":26},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":26.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":27},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":27.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":28}]'::jsonb, 130),
  ('m07', 'Relaxed Linen Shirt', 'men', 'Shirt', 'shirt', 3600, null, null, null, 'Garment-washed linen, camp collar', 'Relaxed and airy', 'Machine wash cold, wear the wrinkles', '[{"n":"Chalk","h":"#EDE8DE"},{"n":"Sea","h":"#7C9AA6"},{"n":"Olive","h":"#5E6448"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":27},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":27.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":28},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":28.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":29}]'::jsonb, 140),
  ('m08', 'Crew Sweatshirt', 'men', 'Sweatshirt', 'sweat', 3300, null, null, null, 'Brushed-back fleece, 350gsm', 'Regular with ribbed cuffs and hem', 'Machine wash cold, dry flat', '[{"n":"Grey Melange","h":"#B3B6B2"},{"n":"Pine","h":"#33544B"},{"n":"Black","h":"#1C1E20"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":25.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":26},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":26.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":27},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":27.5}]'::jsonb, 150),
  ('r01', 'Off White Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/offwhite-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Off White Cream","h":"#F2EBDD"}]'::jsonb, '[{"size":"M","chestMin":36,"chestMax":38.5,"length":27,"stock":2}]'::jsonb, 160),
  ('r03', 'Let’s Get Exploring Print Tee', 'men', 'T-Shirt', 'tee', 180, null, 'New', 'images/exploring-tee.jpg', 'Cotton jersey with a white front print', 'Regular, straight body', 'Wash inside out, cold water, do not iron the print', '[{"n":"Black","h":"#141414"}]'::jsonb, '[{"size":"XXS","chestMin":30,"chestMax":32.5,"length":24,"stock":1}]'::jsonb, 170),
  ('r04', 'Grey Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/grey-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Charcoal Grey","h":"#565A5E"}]'::jsonb, '[{"size":"XL","chestMin":40,"chestMax":42.5,"length":31,"stock":2}]'::jsonb, 180),
  ('r02', 'Black Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/black-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Black","h":"#1C1E20"}]'::jsonb, '[{"size":"S","chestMin":34,"chestMax":36.5,"length":27,"stock":1},{"size":"M","chestMin":36,"chestMax":38.5,"length":27,"stock":1},{"size":"L","chestMin":38,"chestMax":40.5,"length":29,"stock":1}]'::jsonb, 190)
on conflict (slug) do nothing;
