-- Dream of All — কোডে লেখা প্রোডাক্টগুলো ডেটাবেজে তোলার স্ক্রিপ্ট
-- Supabase → SQL Editor → New query → পুরোটা পেস্ট করে Run করুন। একবারই চালাবেন।

insert into public.products
  (slug, name, gender, type, shape, price, old_price, tag, img, fabric, fit, care, colors, sizes, sort)
values
  ('w04', 'Boxy Cotton Tee', 'women', 'T-Shirt', 'tee', 1450, null, 'Best seller', null, 'Combed organic cotton, 220gsm', 'Boxy, sits at the hip', 'Machine wash warm, tumble low', '[{"n":"White","h":"#F4F2EC"},{"n":"Black","h":"#1C1E20"},{"n":"Sage","h":"#94A88F"},{"n":"Butter","h":"#E7CE94"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":24.5},{"size":"S","chestMin":32.5,"chestMax":35,"length":25},{"size":"M","chestMin":35,"chestMax":37.5,"length":25.5},{"size":"L","chestMin":37.5,"chestMax":40,"length":26},{"size":"XL","chestMin":40,"chestMax":43,"length":26.5}]'::jsonb, 0),
  ('w08', 'Cropped Loopback Sweat', 'women', 'Sweatshirt', 'crop', 2900, null, null, null, 'Loopback cotton terry, 320gsm', 'Cropped at the waist, ribbed hem', 'Wash inside out, dry flat', '[{"n":"Grey Melange","h":"#B3B6B2"},{"n":"Ecru","h":"#E3DCCC"},{"n":"Pine","h":"#33544B"}]'::jsonb, '[{"size":"XS","chestMin":30,"chestMax":32.5,"length":17.5},{"size":"S","chestMin":32.5,"chestMax":35,"length":18},{"size":"M","chestMin":35,"chestMax":37.5,"length":18.5},{"size":"L","chestMin":37.5,"chestMax":40,"length":19},{"size":"XL","chestMin":40,"chestMax":43,"length":19.5}]'::jsonb, 10),
  ('m01', 'Heavy Cotton Crew Tee', 'men', 'T-Shirt', 'tee', 1350, null, 'Best seller', null, 'Ring-spun cotton, 240gsm, ribbed collar', 'Regular, straight body', 'Machine wash warm, tumble low', '[{"n":"White","h":"#F4F2EC"},{"n":"Black","h":"#1C1E20"},{"n":"Navy","h":"#2A3A50"},{"n":"Rust","h":"#A65B3D"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":24.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":25},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":25.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":26},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":26.5}]'::jsonb, 20),
  ('m03', 'Piqué Polo', 'men', 'Polo', 'polo', 2250, null, null, null, 'Cotton piqué with a flat-knit collar', 'Trim, sits at the hip', 'Machine wash cold, reshape damp', '[{"n":"Forest","h":"#3B5A46"},{"n":"Chalk","h":"#EDE8DE"},{"n":"Charcoal","h":"#3A3E42"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":26.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":27},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":27.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":28},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":28.5}]'::jsonb, 30),
  ('m05', 'Loopback Hoodie', 'men', 'Sweatshirt', 'hoodie', 4100, null, null, null, 'Heavyweight loopback terry, 400gsm', 'Regular, kangaroo pocket', 'Wash inside out, dry flat', '[{"n":"Charcoal","h":"#35393B"},{"n":"Oat","h":"#DDD2BE"},{"n":"Navy","h":"#2A3A50"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":26},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":26.5},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":27},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":27.5},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":28}]'::jsonb, 40),
  ('m08', 'Crew Sweatshirt', 'men', 'Sweatshirt', 'sweat', 3300, null, null, null, 'Brushed-back fleece, 350gsm', 'Regular with ribbed cuffs and hem', 'Machine wash cold, dry flat', '[{"n":"Grey Melange","h":"#B3B6B2"},{"n":"Pine","h":"#33544B"},{"n":"Black","h":"#1C1E20"}]'::jsonb, '[{"size":"S","chestMin":35,"chestMax":37.5,"length":25.5},{"size":"M","chestMin":37.5,"chestMax":40.5,"length":26},{"size":"L","chestMin":40.5,"chestMax":43.5,"length":26.5},{"size":"XL","chestMin":43.5,"chestMax":46.5,"length":27},{"size":"XXL","chestMin":46.5,"chestMax":50,"length":27.5}]'::jsonb, 50),
  ('r01', 'Off White Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/offwhite-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Off White Cream","h":"#F2EBDD"}]'::jsonb, '[{"size":"M","chestMin":36,"chestMax":38.5,"length":27,"stock":2}]'::jsonb, 60),
  ('r03', 'Let’s Get Exploring Print Tee', 'men', 'T-Shirt', 'tee', 180, null, 'New', 'images/exploring-tee.jpg', 'Cotton jersey with a white front print', 'Regular, straight body', 'Wash inside out, cold water, do not iron the print', '[{"n":"Black","h":"#141414"}]'::jsonb, '[{"size":"XXS","chestMin":30,"chestMax":32.5,"length":24,"stock":1}]'::jsonb, 70),
  ('r04', 'Grey Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/grey-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Charcoal Grey","h":"#565A5E"}]'::jsonb, '[{"size":"XL","chestMin":40,"chestMax":42.5,"length":31,"stock":2}]'::jsonb, 80),
  ('r02', 'Black Cotton Tee', 'men', 'T-Shirt', 'tee', 180, null, null, 'images/black-tee.jpg', 'Cotton jersey, ribbed crew neck', 'Regular, straight body', 'Machine wash cold, tumble dry low', '[{"n":"Black","h":"#1C1E20"}]'::jsonb, '[{"size":"S","chestMin":34,"chestMax":36.5,"length":27,"stock":1},{"size":"M","chestMin":36,"chestMax":38.5,"length":27,"stock":1},{"size":"L","chestMin":38,"chestMax":40.5,"length":29,"stock":1}]'::jsonb, 90),
  ('r05', 'Orange Reflective Stripe Tee', 'men', 'T-Shirt', 'tee', 180, null, 'New', 'images/orange-reflective-tee.jpg', 'Cotton jersey with a white reflective chest stripe', 'Regular, straight body', 'Wash inside out, cold water, do not iron the stripe', '[{"n":"Safety Orange","h":"#FA7002"}]'::jsonb, '[{"size":"S","chestMin":36,"chestMax":38.5,"length":28,"stock":1},{"size":"L","chestMin":42,"chestMax":44.5,"length":29,"stock":2},{"size":"XL","chestMin":46,"chestMax":48.5,"length":29,"stock":1},{"size":"XXL","chestMin":48,"chestMax":50.5,"length":30,"stock":1}]'::jsonb, 100),
  ('r06', 'Walk Me Bicycle Print Tee', 'men', 'T-Shirt', 'tee', 180, null, 'New', 'images/royalblue-walk-tee.jpg', 'Cotton jersey with a front bicycle print', 'Regular, straight body', 'Wash inside out, cold water, do not iron the print', '[{"n":"Royal Blue","h":"#19348C"}]'::jsonb, '[{"size":"XL","chestMin":44,"chestMax":46.5,"length":29,"stock":1}]'::jsonb, 110),
  ('r07', 'Royal Blue Stripe Band Tee', 'men', 'T-Shirt', 'tee', 180, null, 'New', 'images/royalblue-stripe-tee.jpg', 'Cotton jersey with a printed stripe band across the chest', 'Regular, straight body', 'Wash inside out, cold water, do not iron the print', '[{"n":"Royal Blue","h":"#12318A"}]'::jsonb, '[{"size":"XL","chestMin":44,"chestMax":46.5,"length":29,"stock":1}]'::jsonb, 120)
on conflict (slug) do nothing;
